//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PositionEmployee> PositionEmployee { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Technology> Technology { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WhatCan> WhatCan { get; set; }
    }
}
