//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionEmployee
    {
        public int id { get; set; }
        public int IDPosition { get; set; }
        public int IDEmployee { get; set; }
        public Nullable<System.DateTime> DateOfAdopting { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual Position Position { get; set; }
    }
}
